Create full website
EvansSnave/space-traveler pull request #26
Opened 2023-08-20 04:19 UTC by EvansSnave

-implemented react-redux
-Implemented redux toolkit
-Missions and rockets retrieved from API
-Style similar to the given design.
-Reserve and cancel reservation rocket
-Join and leave missions

2023-08-20 04:28 UTC, ademibowale reviewed
Hi @ademibowale,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project that has no commit or contribution from your coding partner, This milestone is a [pair-programming] kindly contact your partner to work as a team on this milestone and resubmit

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-08-20 04:40 UTC, ademibowale reviewed
Hi @EvansSnave ,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project invalid project with no contribution as this is a pair program project, attach your screenshot that indicates you are alone or evidence from the student success that shows that you don't have a coding partner.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-08-20 04:43 UTC, EvansSnave commented
I have been working ALONE
![image](https://github.com/EvansSnave/space-traveler/assets/127534196/d863b781-a0b0-4fad-806e-0f19919d7d12)

2023-08-20 06:17 UTC, ademibowale requested changes
## STATUS: Changes Required :recycle:

### Hi @EvansSnave , 👋 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.tenor.com/isiLRnxz3zwAAAAM/cat-driving-serious.gif" width="500px" height="300px">

### To Highlight 🥇

- Descriptive Pull Request title and summary. ✔️
- Form uses the action and method attribute to integrate with [formspree service](https://formspree.io/html). ✔️
- Input fields have the required attribute to activate the validation ✔️
- Max-length attribute Used on the input ✔️
- Pair-programming collaborative activity ✔️
- Good use of Github flow ✔️

### Changes Required

- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @Adebowale ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-20 06:17 UTC, ademibowale commented on src/pages/myProfile.jsx
> +  const joinedMissions = missions.filter((mission) => mission.reserved);
- [ ] Hello you have done a great job on thi milestone ,i clone your project several time with different ideal but you page not display or render anything on screen ,after i check your code base i can see that you didnt import the myProfile in your myProfile.jsx .so this make the page nor render kindly fix it

2023-08-20 06:17 UTC, ademibowale commented on src/components/navigation.jsx
> +          <img className="logo300" src={logo} alt="Space Traveler" />
- [ ] From the missionList.jsx you have not import the file fromthe components kindly fix it to make your page render and visible it display not on the screen when i clone it severally ,please kindly fix it.

2023-08-20 06:17 UTC, ademibowale commented on src/components/MissionList.jsx
> +  const handleJoinMission = (missionId) => {
- [ ] From the missionList.jsx youA have not import the file fromthe components kindly fix it to make your page render and visible it display not on the screen when i clone it severally ,please kindly fix it.

2023-08-20 07:14 UTC, EvansSnave commented
You took forever to make the review. Thank you for making me repeat the
module.

El dom, 20 ago 2023 a las 1:17, Adebowale Adegboye Monsur (<
***@***.***>) escribió:

> ***@***.**** requested changes on this pull request.
> STATUS: Changes Required ♻️ Hi @EvansSnave <https://github.com/EvansSnave>
> , 👋
>
> Good job so far!
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
>
>
> <https://camo.githubusercontent.com/cf6e3cd7e4cbb865d88dd58069a57b1731d1a2ed019204f6cadf0414d954710e/68747470733a2f2f6d656469612e74656e6f722e636f6d2f6973694c526e787a337a77414141414d2f6361742d64726976696e672d736572696f75732e676966>
> To Highlight 🥇
>
>    - Descriptive Pull Request title and summary. ✔️
>    - Form uses the action and method attribute to integrate with formspree
>    service <https://formspree.io/html>. ✔️
>    - Input fields have the required attribute to activate the validation
>    ✔️
>    - Max-length attribute Used on the input ✔️
>    - Pair-programming collaborative activity ✔️
>    - Good use of Github flow ✔️
>
> Changes Required
>
>    - *Please check the comments under the review.*
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me on( @Adebowale <https://github.com/Adebowale>
> ) in your question so I can receive the notification.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In src/pages/myProfile.jsx
> <https://github.com/EvansSnave/space-traveler/pull/26#discussion_r1299309844>
> :
>
> > +import React from 'react';
> +import { useSelector } from 'react-redux';
> +import Table from 'react-bootstrap/Table';
> +
> +const MyProfile = () => {
> +  const rockets = useSelector((state) => state.rockets);
> +  const missions = useSelector((state) => state.missions.missions);
> +  const reservedRockets = rockets.filter((rocket) => rocket.reserved);
> +  const joinedMissions = missions.filter((mission) => mission.reserved);
>
>
>    - Hello you have done a great job on thi milestone ,i clone your
>    project several time with different ideal but you page not display or
>    render anything on screen ,after i check your code base i can see that you
>    didnt import the myProfile in your myProfile.jsx .so this make the page nor
>    render kindly fix it
>
> ------------------------------
>
> In src/components/navigation.jsx
> <https://github.com/EvansSnave/space-traveler/pull/26#discussion_r1299310211>
> :
>
> > +import { NavLink } from 'react-router-dom';
> +import logo from '../assets/logo.png';
> +import '../styles/navigation.css';
> +
> +function NavBar() {
> +  return (
> +    <nav>
> +      <div className="parentcontainer300">
> +        <div className="container300">
> +          <img className="logo300" src={logo} alt="Space Traveler" />
>
>
>    - From the missionList.jsx you have not import the file fromthe
>    components kindly fix it to make your page render and visible it display
>    not on the screen when i clone it severally ,please kindly fix it.
>
> ------------------------------
>
> In src/components/MissionList.jsx
> <https://github.com/EvansSnave/space-traveler/pull/26#discussion_r1299310367>
> :
>
> > +import React from 'react';
> +import PropTypes from 'prop-types';
> +import Table from 'react-bootstrap/Table';
> +import Button from 'react-bootstrap/Button';
> +import Badge from 'react-bootstrap/Badge';
> +import { useDispatch } from 'react-redux';
> +import { reserveMission, leaveMission } from '../redux/missions/missionsSlice';
> +import '../styles/MissionList.css';
> +
> +const MissionList = ({ missions }) => {
> +  const dispatch = useDispatch();
> +
> +  const handleJoinMission = (missionId) => {
>
>
>    - From the missionList.jsx youA have not import the file fromthe
>    components kindly fix it to make your page render and visible it display
>    not on the screen when i clone it severally ,please kindly fix it.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/EvansSnave/space-traveler/pull/26#pullrequestreview-1585805258>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A6NAI5ASM7WOP4ENGVPGZ7TXWGTX3ANCNFSM6AAAAAA3XALNQI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-08-20 07:54 UTC, ademibowale commented
No not what you think ,when review any project we dont rush especially a
capstone project like this yours,that's why it's good to submit a project
at a good time you submitted your project at the dead time .so it wasn't my
fault and if I approve it like that mv might detect that which might create
a problem so I have to follow the requirements and make sure the project
works as expected.
I am so sorry assuming there is still time we can both fix any technical
issues and resubmit then get it approve.

On Sun, Aug 20, 2023, 8:14 AM Kevin Cruz ***@***.***> wrote:

> You took forever to make the review. Thank you for making me repeat the
> module.
>
> El dom, 20 ago 2023 a las 1:17, Adebowale Adegboye Monsur (<
> ***@***.***>) escribió:
>
> > ***@***.**** requested changes on this pull request.
> > STATUS: Changes Required ♻️ Hi @EvansSnave <
> https://github.com/EvansSnave>
> > , 👋
> >
> > Good job so far!
> > There are some issues that you still need to work on to go to the next
> > project but you are almost there!
> >
> >
> > <
> https://camo.githubusercontent.com/cf6e3cd7e4cbb865d88dd58069a57b1731d1a2ed019204f6cadf0414d954710e/68747470733a2f2f6d656469612e74656e6f722e636f6d2f6973694c526e787a337a77414141414d2f6361742d64726976696e672d736572696f75732e676966>
>
> > To Highlight 🥇
> >
> > - Descriptive Pull Request title and summary. ✔️
> > - Form uses the action and method attribute to integrate with formspree
> > service <https://formspree.io/html>. ✔️
> > - Input fields have the required attribute to activate the validation
> > ✔️
> > - Max-length attribute Used on the input ✔️
> > - Pair-programming collaborative activity ✔️
> > - Good use of Github flow ✔️
> >
> > Changes Required
> >
> > - *Please check the comments under the review.*
> >
> > Optional suggestions
> >
> > *Every comment with the [OPTIONAL] prefix won't stop the approval of
> this
> > PR. However, I strongly recommend you to take them into account as they
> can
> > make your code better. Some of them were simply missed by the previous
> > reviewer and addressing them will really improve your application.*
> >
> > Cheers and Happy coding!👏👏👏
> >
> > Feel free to leave any questions or comments in the PR thread if
> something
> > is not 100% clear.
> > Please, remember to tag me on( @Adebowale <https://github.com/Adebowale>
>
> > ) in your question so I can receive the notification.
> > ------------------------------
> >
> > *As described in the Code reviews limits policy
> > <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you
> have a
> > limited number of reviews per project (check the exact number in your
> > Dashboard). If you think that the code review was not fair, you can
> request
> > a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> > ------------------------------
> >
> > In src/pages/myProfile.jsx
> > <
> https://github.com/EvansSnave/space-traveler/pull/26#discussion_r1299309844>
>
> > :
> >
> > > +import React from 'react';
> > +import { useSelector } from 'react-redux';
> > +import Table from 'react-bootstrap/Table';
> > +
> > +const MyProfile = () => {
> > + const rockets = useSelector((state) => state.rockets);
> > + const missions = useSelector((state) => state.missions.missions);
> > + const reservedRockets = rockets.filter((rocket) => rocket.reserved);
> > + const joinedMissions = missions.filter((mission) => mission.reserved);
> >
> >
> > - Hello you have done a great job on thi milestone ,i clone your
> > project several time with different ideal but you page not display or
> > render anything on screen ,after i check your code base i can see that
> you
> > didnt import the myProfile in your myProfile.jsx .so this make the page
> nor
> > render kindly fix it
> >
> > ------------------------------
> >
> > In src/components/navigation.jsx
> > <
> https://github.com/EvansSnave/space-traveler/pull/26#discussion_r1299310211>
>
> > :
> >
> > > +import { NavLink } from 'react-router-dom';
> > +import logo from '../assets/logo.png';
> > +import '../styles/navigation.css';
> > +
> > +function NavBar() {
> > + return (
> > + <nav>
> > + <div className="parentcontainer300">
> > + <div className="container300">
> > + <img className="logo300" src={logo} alt="Space Traveler" />
> >
> >
> > - From the missionList.jsx you have not import the file fromthe
> > components kindly fix it to make your page render and visible it display
> > not on the screen when i clone it severally ,please kindly fix it.
> >
> > ------------------------------
> >
> > In src/components/MissionList.jsx
> > <
> https://github.com/EvansSnave/space-traveler/pull/26#discussion_r1299310367>
>
> > :
> >
> > > +import React from 'react';
> > +import PropTypes from 'prop-types';
> > +import Table from 'react-bootstrap/Table';
> > +import Button from 'react-bootstrap/Button';
> > +import Badge from 'react-bootstrap/Badge';
> > +import { useDispatch } from 'react-redux';
> > +import { reserveMission, leaveMission } from
> '../redux/missions/missionsSlice';
> > +import '../styles/MissionList.css';
> > +
> > +const MissionList = ({ missions }) => {
> > + const dispatch = useDispatch();
> > +
> > + const handleJoinMission = (missionId) => {
> >
> >
> > - From the missionList.jsx youA have not import the file fromthe
> > components kindly fix it to make your page render and visible it display
> > not on the screen when i clone it severally ,please kindly fix it.
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/EvansSnave/space-traveler/pull/26#pullrequestreview-1585805258>,
>
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/A6NAI5ASM7WOP4ENGVPGZ7TXWGTX3ANCNFSM6AAAAAA3XALNQI>
>
> > .
> > You are receiving this because you were mentioned.Message ID:
> > ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/EvansSnave/space-traveler/pull/26#issuecomment-1685207618>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWBMZ7DIFXH5WLW4EVUUECDXWG2OTANCNFSM6AAAAAA3XALNQI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-08-20 07:59 UTC, ademibowale commented
Whenever you work on a project and you are stucked never stay too long on
it without contact people on slack ,so you can fix it together, your
project you are giving 6 days to complete from monday to Saturday yet you
submitted on Saturday last minit .too late

On Sun, Aug 20, 2023, 8:54 AM Adebowale Adegboye <
***@***.***> wrote:

> No not what you think ,when review any project we dont rush especially a
> capstone project like this yours,that's why it's good to submit a project
> at a good time you submitted your project at the dead time .so it wasn't my
> fault and if I approve it like that mv might detect that which might create
> a problem so I have to follow the requirements and make sure the project
> works as expected.
> I am so sorry assuming there is still time we can both fix any technical
> issues and resubmit then get it approve.
>
> On Sun, Aug 20, 2023, 8:14 AM Kevin Cruz ***@***.***> wrote:
>
>> You took forever to make the review. Thank you for making me repeat the
>> module.
>>
>> El dom, 20 ago 2023 a las 1:17, Adebowale Adegboye Monsur (<
>> ***@***.***>) escribió:
>>
>> > ***@***.**** requested changes on this pull request.
>> > STATUS: Changes Required ♻️ Hi @EvansSnave <
>> https://github.com/EvansSnave>
>> > , 👋
>> >
>> > Good job so far!
>> > There are some issues that you still need to work on to go to the next
>> > project but you are almost there!
>> >
>> >
>> > <
>> https://camo.githubusercontent.com/cf6e3cd7e4cbb865d88dd58069a57b1731d1a2ed019204f6cadf0414d954710e/68747470733a2f2f6d656469612e74656e6f722e636f6d2f6973694c526e787a337a77414141414d2f6361742d64726976696e672d736572696f75732e676966>
>>
>> > To Highlight 🥇
>> >
>> > - Descriptive Pull Request title and summary. ✔️
>> > - Form uses the action and method attribute to integrate with formspree
>> > service <https://formspree.io/html>. ✔️
>> > - Input fields have the required attribute to activate the validation
>> > ✔️
>> > - Max-length attribute Used on the input ✔️
>> > - Pair-programming collaborative activity ✔️
>> > - Good use of Github flow ✔️
>> >
>> > Changes Required
>> >
>> > - *Please check the comments under the review.*
>> >
>> > Optional suggestions
>> >
>> > *Every comment with the [OPTIONAL] prefix won't stop the approval of
>> this
>> > PR. However, I strongly recommend you to take them into account as they
>> can
>> > make your code better. Some of them were simply missed by the previous
>> > reviewer and addressing them will really improve your application.*
>> >
>> > Cheers and Happy coding!👏👏👏
>> >
>> > Feel free to leave any questions or comments in the PR thread if
>> something
>> > is not 100% clear.
>> > Please, remember to tag me on( @Adebowale <https://github.com/Adebowale>
>>
>> > ) in your question so I can receive the notification.
>> > ------------------------------
>> >
>> > *As described in the Code reviews limits policy
>> > <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you
>> have a
>> > limited number of reviews per project (check the exact number in your
>> > Dashboard). If you think that the code review was not fair, you can
>> request
>> > a second opinion using this form <
>> https://airtable.com/shrQAqnBwek5a0O0s>.*
>> > ------------------------------
>> >
>> > In src/pages/myProfile.jsx
>> > <
>> https://github.com/EvansSnave/space-traveler/pull/26#discussion_r1299309844>
>>
>> > :
>> >
>> > > +import React from 'react';
>> > +import { useSelector } from 'react-redux';
>> > +import Table from 'react-bootstrap/Table';
>> > +
>> > +const MyProfile = () => {
>> > + const rockets = useSelector((state) => state.rockets);
>> > + const missions = useSelector((state) => state.missions.missions);
>> > + const reservedRockets = rockets.filter((rocket) => rocket.reserved);
>> > + const joinedMissions = missions.filter((mission) =>
>> mission.reserved);
>> >
>> >
>> > - Hello you have done a great job on thi milestone ,i clone your
>> > project several time with different ideal but you page not display or
>> > render anything on screen ,after i check your code base i can see that
>> you
>> > didnt import the myProfile in your myProfile.jsx .so this make the page
>> nor
>> > render kindly fix it
>> >
>> > ------------------------------
>> >
>> > In src/components/navigation.jsx
>> > <
>> https://github.com/EvansSnave/space-traveler/pull/26#discussion_r1299310211>
>>
>> > :
>> >
>> > > +import { NavLink } from 'react-router-dom';
>> > +import logo from '../assets/logo.png';
>> > +import '../styles/navigation.css';
>> > +
>> > +function NavBar() {
>> > + return (
>> > + <nav>
>> > + <div className="parentcontainer300">
>> > + <div className="container300">
>> > + <img className="logo300" src={logo} alt="Space Traveler" />
>> >
>> >
>> > - From the missionList.jsx you have not import the file fromthe
>> > components kindly fix it to make your page render and visible it
>> display
>> > not on the screen when i clone it severally ,please kindly fix it.
>> >
>> > ------------------------------
>> >
>> > In src/components/MissionList.jsx
>> > <
>> https://github.com/EvansSnave/space-traveler/pull/26#discussion_r1299310367>
>>
>> > :
>> >
>> > > +import React from 'react';
>> > +import PropTypes from 'prop-types';
>> > +import Table from 'react-bootstrap/Table';
>> > +import Button from 'react-bootstrap/Button';
>> > +import Badge from 'react-bootstrap/Badge';
>> > +import { useDispatch } from 'react-redux';
>> > +import { reserveMission, leaveMission } from
>> '../redux/missions/missionsSlice';
>> > +import '../styles/MissionList.css';
>> > +
>> > +const MissionList = ({ missions }) => {
>> > + const dispatch = useDispatch();
>> > +
>> > + const handleJoinMission = (missionId) => {
>> >
>> >
>> > - From the missionList.jsx youA have not import the file fromthe
>> > components kindly fix it to make your page render and visible it
>> display
>> > not on the screen when i clone it severally ,please kindly fix it.
>> >
>> > —
>> > Reply to this email directly, view it on GitHub
>> > <
>> https://github.com/EvansSnave/space-traveler/pull/26#pullrequestreview-1585805258>,
>>
>> > or unsubscribe
>> > <
>> https://github.com/notifications/unsubscribe-auth/A6NAI5ASM7WOP4ENGVPGZ7TXWGTX3ANCNFSM6AAAAAA3XALNQI>
>>
>> > .
>> > You are receiving this because you were mentioned.Message ID:
>> > ***@***.***>
>> >
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/EvansSnave/space-traveler/pull/26#issuecomment-1685207618>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AWBMZ7DIFXH5WLW4EVUUECDXWG2OTANCNFSM6AAAAAA3XALNQI>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>

2023-08-20 08:44 UTC, ademibowale commented
Hello Kevin  ,
I am just thinking about you because there was a time I was like you at
that stage i understand how you will be feeling to repeated a module, i
have a suggestion for you please .kindly write Marco Lizza the student
success explain how difficult it's for you only to complete the project at
a given period without pearner, how you encounter difficulties during the
project which you resolve by yourself while you contacted  different
developers on slack but many are too busy to help ,request for additional
week or days if possible just a day to resubmit your project that you have
done and completed the project with all changes requested have been
resolved, ask them to give you just Monday to get your project approve that
you cant just afford to repeat the module, repeating a module can disable a
mora making you weak in learning because you so much devoted in learning
and you dont want anything to discourage you, please write the student
success and make sure you tag maco Lizza with the message  ,you send the
mail via the last email you recieve from Marco lizza last by hit the reply
to write him if he can consider you .

Thank you .

On Sun, Aug 20, 2023, 8:14 AM Kevin Cruz ***@***.***> wrote:

> You took forever to make the review. Thank you for making me repeat the
> module.
>
> El dom, 20 ago 2023 a las 1:17, Adebowale Adegboye Monsur (<
> ***@***.***>) escribió:
>
> > ***@***.**** requested changes on this pull request.
> > STATUS: Changes Required ♻️ Hi @EvansSnave <
> https://github.com/EvansSnave>
> > , 👋
> >
> > Good job so far!
> > There are some issues that you still need to work on to go to the next
> > project but you are almost there!
> >
> >
> > <
> https://camo.githubusercontent.com/cf6e3cd7e4cbb865d88dd58069a57b1731d1a2ed019204f6cadf0414d954710e/68747470733a2f2f6d656469612e74656e6f722e636f6d2f6973694c526e787a337a77414141414d2f6361742d64726976696e672d736572696f75732e676966>
>
> > To Highlight 🥇
> >
> > - Descriptive Pull Request title and summary. ✔️
> > - Form uses the action and method attribute to integrate with formspree
> > service <https://formspree.io/html>. ✔️
> > - Input fields have the required attribute to activate the validation
> > ✔️
> > - Max-length attribute Used on the input ✔️
> > - Pair-programming collaborative activity ✔️
> > - Good use of Github flow ✔️
> >
> > Changes Required
> >
> > - *Please check the comments under the review.*
> >
> > Optional suggestions
> >
> > *Every comment with the [OPTIONAL] prefix won't stop the approval of
> this
> > PR. However, I strongly recommend you to take them into account as they
> can
> > make your code better. Some of them were simply missed by the previous
> > reviewer and addressing them will really improve your application.*
> >
> > Cheers and Happy coding!👏👏👏
> >
> > Feel free to leave any questions or comments in the PR thread if
> something
> > is not 100% clear.
> > Please, remember to tag me on( @Adebowale <https://github.com/Adebowale>
>
> > ) in your question so I can receive the notification.
> > ------------------------------
> >
> > *As described in the Code reviews limits policy
> > <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you
> have a
> > limited number of reviews per project (check the exact number in your
> > Dashboard). If you think that the code review was not fair, you can
> request
> > a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> > ------------------------------
> >
> > In src/pages/myProfile.jsx
> > <
> https://github.com/EvansSnave/space-traveler/pull/26#discussion_r1299309844>
>
> > :
> >
> > > +import React from 'react';
> > +import { useSelector } from 'react-redux';
> > +import Table from 'react-bootstrap/Table';
> > +
> > +const MyProfile = () => {
> > + const rockets = useSelector((state) => state.rockets);
> > + const missions = useSelector((state) => state.missions.missions);
> > + const reservedRockets = rockets.filter((rocket) => rocket.reserved);
> > + const joinedMissions = missions.filter((mission) => mission.reserved);
> >
> >
> > - Hello you have done a great job on thi milestone ,i clone your
> > project several time with different ideal but you page not display or
> > render anything on screen ,after i check your code base i can see that
> you
> > didnt import the myProfile in your myProfile.jsx .so this make the page
> nor
> > render kindly fix it
> >
> > ------------------------------
> >
> > In src/components/navigation.jsx
> > <
> https://github.com/EvansSnave/space-traveler/pull/26#discussion_r1299310211>
>
> > :
> >
> > > +import { NavLink } from 'react-router-dom';
> > +import logo from '../assets/logo.png';
> > +import '../styles/navigation.css';
> > +
> > +function NavBar() {
> > + return (
> > + <nav>
> > + <div className="parentcontainer300">
> > + <div className="container300">
> > + <img className="logo300" src={logo} alt="Space Traveler" />
> >
> >
> > - From the missionList.jsx you have not import the file fromthe
> > components kindly fix it to make your page render and visible it display
> > not on the screen when i clone it severally ,please kindly fix it.
> >
> > ------------------------------
> >
> > In src/components/MissionList.jsx
> > <
> https://github.com/EvansSnave/space-traveler/pull/26#discussion_r1299310367>
>
> > :
> >
> > > +import React from 'react';
> > +import PropTypes from 'prop-types';
> > +import Table from 'react-bootstrap/Table';
> > +import Button from 'react-bootstrap/Button';
> > +import Badge from 'react-bootstrap/Badge';
> > +import { useDispatch } from 'react-redux';
> > +import { reserveMission, leaveMission } from
> '../redux/missions/missionsSlice';
> > +import '../styles/MissionList.css';
> > +
> > +const MissionList = ({ missions }) => {
> > + const dispatch = useDispatch();
> > +
> > + const handleJoinMission = (missionId) => {
> >
> >
> > - From the missionList.jsx youA have not import the file fromthe
> > components kindly fix it to make your page render and visible it display
> > not on the screen when i clone it severally ,please kindly fix it.
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/EvansSnave/space-traveler/pull/26#pullrequestreview-1585805258>,
>
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/A6NAI5ASM7WOP4ENGVPGZ7TXWGTX3ANCNFSM6AAAAAA3XALNQI>
>
> > .
> > You are receiving this because you were mentioned.Message ID:
> > ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/EvansSnave/space-traveler/pull/26#issuecomment-1685207618>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWBMZ7DIFXH5WLW4EVUUECDXWG2OTANCNFSM6AAAAAA3XALNQI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-10-02 23:28 UTC, nicupop729 reviewed
Hello team 👋,

_This is a manual review._

Please note that during pair programming activities, we cannot utilize previously approved old repositories.
Let's make the most of our group project and collaborate to develop this fantastic project.
Please establish a completely new repository and work on it as a team. Each of you should create the rockets, missions, and dragons sections accordingly.
Ensure that the tasks are evenly divided among you using the Kanban board.

Best of luck with your new project! :four_leaf_clover:

Keep rocking 🚀!

2023-10-06 22:48 UTC, closed without merging